spring:
  jpa:
    show-sql: true
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/my_db
    username: bestuser
    password: bestuser
  mvc:
    view:
      prefix: /WEB_INF/jsp
      suffix: .jsp


